### ISSUE TITLE
Fix failing tests on Windows 11 (ARM emulated through Parallels on Mac M1)

### ISSUE THREAD

**Issue by cmin764** [robocorp/robocorp#105]
Failing tests:
```
FAILED tests/robocorp_windows_tests/test_robocorp_windows_chrome.py::test_multiple_interactions
FAILED tests/robocorp_windows_tests/test_robocorp_windows_explorer.py::test_copy_with_explorer
```

All of them ending in an `ElementNotFound` error due to system's UI different layouts. If not simple/stable, then mark the tests as `@xfail`.

**Comment by cmin764** [comment]
Lots of logs printed until the timeout passes for the Chrome failing test, swallowing the terminal limit to display messages.

**Comment by cmin764** [comment]
@fabioz observation: the test started to take too long in CI due to a change in Chrome. On Cosmin's side, might be an accessibility issue.

Would the value of the testing coverage drop if we remove this test. Or can we think of better, faster and more compatible alternatives for the test itself?

**Comment by fabioz** [comment]
I think we need to support those (testing chrome is almost the same as testing electron). 

i.e.: Those are the same pains our customers will have, so, marking as `@xfail` is not a reasonable solution IMHO.
