### ISSUE TITLE
`windows_run` sometimes types the text outside the "Windows Run" widget

### ISSUE THREAD

**Issue by mmokko** [robocorp/robocorp#110]
This happens quite often on a slow machine. The text is typed where cursor was when the execution was started.

Could we add an API to open the application via subprocess?

There also used to be in the old rpaframework desktop library: https://rpaframework.org/libraries/desktop/ keyword: Open Application. This opened the executable in given path.

**Comment by kariharju** [comment]
Agree, 

Having the [open_application](https://robocorp.com/docs/python/rpa-framework/rpa-desktop/api#method-openapplication) and the [close_application](https://robocorp.com/docs/python/rpa-framework/rpa-desktop/api#method-closeapplication) implementations directly in robocorp-windows makes for simpler and more reliable usage as we get the application instance directly without having to always find the windows by locators after starting via Windows Run.

**Comment by cmin764** [comment]
This pair of handlers will be the first to be added in the upcoming `robocorp-desktop` library.

**Comment by OvidiuCode** [comment]
Hey @kariharju @mmokko @cmin764 since this is somehow an old issue I want to confirm that this is still something we want to implement. If we do, @cmin764 made a suggestion to implement this into `robocorp-desktop` library (new library) as this functionality is platform agnostic. What do you think?

**Comment by cmin764** [comment]
> Hey [@kariharju](https://github.com/kariharju) [@mmokko](https://github.com/mmokko) [@cmin764](https://github.com/cmin764) since this is somehow an old issue I want to confirm that this is still something we want to implement. If we do, [@cmin764](https://github.com/cmin764) made a suggestion to implement this into `robocorp-desktop` library (new library) as this functionality is platform agnostic. What do you think?

I endorse that!

Meanwhile, do you think if it helps to add some sort of wait before typing in the text or even better, a window finding loop that waits for the window to appear before typing in?
