### ISSUE TITLE
The main level guide article for the Windows library needs to start with a usage example

### ISSUE THREAD

**Issue by kariharju** [robocorp/robocorp#111]
Source:
https://robocorp.com/docs/python/robocorp/robocorp-windows/guides

Instead of diving into locators etc. the guide sections needs to start with some basic usage example that gets the first 80% onboard and running their first automation.

```
from robocorp.tasks import task
from robocorp import windows

@task
def example_run():
    windows.desktop().windows_run("notepad.exe")
    notepad = windows.find_window('regex:.*Notepad')
    notepad.find('control: "MenuItemControl" and name: "File"').click()
    notepad.close_window()
```

**Comment by cmin764** [comment]
Just quickly added this to active work since I'm already at this topic with: https://github.com/robocorp/robocorp/pull/218
