### ISSUE TITLE
Integration test fails due to `http` deprecation

### ISSUE THREAD

**Issue by cmin764** [robocorp/robocorp#148]
`ImportError: cannot import name 'download' from 'robocorp.http' ` in [job](https://github.com/robocorp/robocorp/actions/runs/7517724402/job/20464207709?pr=147).

Read migration [guide](https://github.com/robocorp/robocorp/tree/master/http) and fix the `invoke test` run.

**Comment by fabioz** [comment]
Fixed in https://github.com/robocorp/robocorp/commit/982be1513d5a72df27967f4b5401c85c212ec8d2
