### ISSUE TITLE
Action Server does not handle output size

### ISSUE THREAD

**Issue by mkorpela** [robocorp/robocorp#152]
### What happened?

* Current Status *

Current Action Server @action has limitless return value size. OpenAI GPT and Large Language Models in general work with limited size tokenized texts.
OpenAI GPT allowed return value size is around 3500 ASCII characters. After that it will just error on Action use.

```python
@action
def kaboom():
    return "A"*10000
```

This means that actions that return too big outputs will always fail from the callers (clients) point of view.

* How should it work *

I propose that Action Server internally truncates the outputs. The exact max size number could be configured in the Web UI.

Reference implementation:
```python
def truncate_output_with_beginning_clue(output: str, max_chars: int = 2000) -> str:
    beginning_clue = "[Cut] "  # A very short clue at the beginning to indicate possible truncation

    if len(output) > max_chars:
        truncated_output = output[:max_chars - len(beginning_clue)]
        chars_missed = len(output) - len(truncated_output)
        truncated_message = f"[+{chars_missed}]"
        return beginning_clue + truncated_output + truncated_message
    else:
        return output
```

### System Info

* 0.0.13 * Python 3.11.5 * OSX *

**Comment by tonnitommi** [comment]
> OpenAI GPT allowed return value size is around 3500 ASCII characters

Doesn't look like GPTs would restrict this anymore (at least there is not an error), but the GPT will not have access to the entire output if it's long. When asking a GPT what it can handle, the response is:

_The maximum length of text I can effectively handle in a single interaction depends on the context of the request. For processing and analyzing text within a single response, I work best with segments up to around 4096 tokens (words and punctuation marks). This limit helps ensure accuracy in my responses and analyses._

Note: Action Server Toolkit for langchain has a truncation in the connector. [Here.](https://github.com/langchain-ai/langchain/blob/e980c14d6a22f41b31d5d7153a3a598148a120de/libs/partners/robocorp/langchain_robocorp/toolkits.py#L252)

**Comment by kariharju** [comment]
This issue has been moved <a href="https://github.com/Sema4AI/actions/issues/43">here</a>, under <a href=https://github.com/Sema4AI/actions>Sema4AI/actions</a> repository.
