### ISSUE TITLE
Exposing large data blobs (such as images) as URLs

### ISSUE THREAD

**Issue by mkorpela** [robocorp/robocorp#153]
### Description

* Current State *

LLMs such as OpenAI ChatGPT can show images with markdown links. LLMs can not work with binary data directly (images, videos, pdfs, excels..) as they are not short tokenized text.

For an action to return an image, that would be displayed by ChatGPT currently a third party hosting service is needed. This then can be used to generate a URL for an image:
![image](https://github.com/robocorp/robocorp/assets/136885/1dbbedd1-81aa-4b6f-8a52-266c69c808ee)

This method adds another service into loop. This is a security concern when dealing with private data. I personally would be much more happy with just Action Server and OpenAI in the loop.

It is also inconvenience as that requires setting up account to that third party service and learning to use their APIs.

### Describe the solution you'd like

I propose that actions and Action Server will provide an sdk to allow exposing large data blobs from actions as GET URL:s.
As working with "large" binary data is pretty common I would think this would be really useful.

```python
from robocorp.actions import action, reference_url

@action
def make_an_image():
    image = ...
    url = reference_url(image)
    return f"Image is at {url}"
```

### Describe alternatives you've considered

Alternative is the use of third party file sharing services or user themselves making their own methods.

**Comment by kariharju** [comment]
This issue has been moved <a href="https://github.com/Sema4AI/actions/issues/44">here</a>, under <a href=https://github.com/Sema4AI/actions>Sema4AI/actions</a> repository.
