### ISSUE TITLE
[Feature]: Ability to give action docs as a structured arguments of the annotation

### ISSUE THREAD

**Issue by mkorpela** [robocorp/robocorp#160]
### Description

Currently action documentation for openapi spec is parsed from the docstring. This requires a special format of docstring to work correctly. Other tools do provide also structured options to more formally define these pieces of information. This leads to higher reliability.

### Describe the solution you'd like

I would like to do this:

```python
@action(description="Produces an excellent greeting for the given person", 
        args={"name": "name of the person to greet"})
def greet(name: str): 
    ..
```

### Describe alternatives you've considered

.

**Comment by fabioz** [comment]
I wouldn't say it leads to higher readability. I'd probably say less readability but with a more structured format -- I'm not against it, but I'm not a fan either ;) 

As a note, we currently support multiple docstring formats (using https://github.com/jsh9/docstring_parser_fork), so, the formats below work (the formats supported are: ReST, Google, Numpydoc-style and Epydoc docstrings). 

```
def greet(name: str):
    '''
    Produces an excellent greeting for the given person.
    :param name: name of the person to greet.
    '''
```

```
def greet(name: str):
    '''
    Produces an excellent greeting for the given person.
    Args:
        name: name of the person to greet.
    '''
```

**Comment by mkorpela** [comment]
> I wouldn't say it leads to higher readability.

.. reliability

**Comment by kariharju** [comment]
Right now I would like to stay in one format: docString in Google Style. There are a zillion options in Python ecosystem and frankly speaking none I have seen is "an actual format", just loose guide-lines that all have so many variants that creating a reliable parser is just a nightmare.

I'd say let's stick with one in support, examples and documentations as much as we can.
