### ISSUE TITLE
Support `@action(reuse_process=True)`

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#166]
Whether an action should be reused could be specified in the `@action`, something as `@action(reuse_process=True)`, as in some actions, it may make sense to reuse it while in others not (the default being the passed command line parameter).

**Comment by kariharju** [comment]
This issue has been moved <a href="https://github.com/Sema4AI/actions/issues/45">here</a>, under <a href=https://github.com/Sema4AI/actions>Sema4AI/actions</a> repository.
