### ISSUE TITLE
Access request headers in the action

### ISSUE THREAD

**Issue by mkorpela** [robocorp/robocorp#167]
## Why

We need to able to pass for example secrets from the execution environment to the action by injecting headers into the requests.

Having request headers easily available on the code level makes this a powerful tool to leverage standard authentication mechanisms.

### Describe the solution you'd like

The `robocorp.actions` library could have a function that allows access to the request headers during action execution.

```
@action
def my_action(request: Request):
    // headers are here
    request.headers
```

**Comment by cmin764** [comment]
Or a proxy/global object to retrieve various request-time info right from FastAPI, like Flask is having:
```python
from robocorp.actions import request

print(request.headers)
```

**Comment by mikahanninen** [comment]
Shouldn't this header information be tied to the action itself so that it would be clear what headers were sent for that action ? If action server can handle multiple actions at the same (threaded) then at the time the action would be accessing headers, it might get headers from wrong action request ?

**Comment by cmin764** [comment]
> Shouldn't this header information be tied to the action itself so that it would be clear what headers were sent for that action ? If action server can handle multiple actions at the same (threaded) then at the time the action would be accessing headers, it might get headers from wrong action request ?

Totally agree! And as long as the `request` object respects its naming (which is bound to the request itself), it should be a proxy object containing info bound to the thread responsible with the single request we're accessing info from. (different info retrieved based on thread)
But the implementation itself can change to fit a simpler development scenario. (so it can be a parameter the decorated action receives if we can do this as a non-breaking change)

**Comment by fabioz** [comment]
I think the main thing is how we're going to handle authentication in general at this point and this is still not completely defined as it depends a lot on how the actual deployment of actions will work (so, waiting for that part: https://github.com/robocorp/robocorp/issues/229 before doing this one).

**Comment by fabioz** [comment]
This was de prioritized for now.

Some work was done already, so, notes below related to what is in pace:
- todo_issue_167_access_headers: test which checks the headers
- `robocorp.actions._request.Request` was created but is not currently used anywhere 
- Commented out code in: `robo\action_server\tests\action_server_tests\resources\no_conda\check_headers\headers_action.py`
