### ISSUE TITLE
Action ability to request user input during execution

### ISSUE THREAD

**Issue by mkorpela** [robocorp/robocorp#174]
### Description

The fact that we are running HTTP server and on the background running the action in a separate process, would allow requesting user input during execution. This is an opportunity.

It can allow things like this
```python
@action
def greeter(name: str) -> str:
    place = request_input(f"Ask from the user: Where are you from {name}?")
    return f"Hello {name} from {place}!"
```

### Describe the solution you'd like

https://github.com/robocorp/actions-cookbook/tree/master/example-user-input

**Comment by tonnitommi** [comment]
Assuming AI Actions are used from another interface such as chatbot/assistant, why would you suddenly move user interaction somewhere else? Or am I missing something? Why would you not split the action and let the "host" system deal with user interaction?

**Comment by kariharju** [comment]
This issue has been moved <a href="https://github.com/Sema4AI/actions/issues/46">here</a>, under <a href=https://github.com/Sema4AI/actions>Sema4AI/actions</a> repository.
