### ISSUE TITLE
Enable auto-reload of actions

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#176]
### Description

If some action changes, we'd like to collect the changes, update the internal definitions and make the new version of the action available automatically (when the user starts the action server with `--reload`).

**Comment by mkorpela** [comment]
Still would / will need manually updating the openapi spec in OpenAI GPT.. :/

So currently the code is reloaded on every call, but the interface changes are not reflected.

**Comment by kariharju** [comment]
This issue has been moved <a href="https://github.com/Sema4AI/actions/issues/47">here</a>, under <a href=https://github.com/Sema4AI/actions>Sema4AI/actions</a> repository.
