### ISSUE TITLE
Async APIs for running actions

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#177]
### Description

The action server currently only has one API to run the actions which is synchronous. Ideally we'd like APIs which allow the action server to start running and then poll for the result (a 2nd step would be issuing a callback when it finishes).

**Comment by tonnitommi** [comment]
Initially, the recommendation for long-running actions is to revert to Robocorp's Process and Control Room stack, which provides [async API](https://robocorp.com/api), webhooks and the ability to poll the results.

We might revisit the relation between Actions and Processes later.

**Comment by kariharju** [comment]
This issue has been moved <a href="https://github.com/Sema4AI/actions/issues/48">here</a>, under <a href=https://github.com/Sema4AI/actions>Sema4AI/actions</a> repository.
