### ISSUE TITLE
Support decorators for `@action`

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#202]
### Target components

action_server, actions

### Description

i.e.: As something as:

```
@my_decorator
@action
def any_action(value: str) -> str:
    ...
```

is the same as:

```
def any_action(value: str) -> str:
    ...

any_action = action(any_action) # at this point we save the reference to the function, so, it doesn't work.
any_action = my_decorator(any_action)
```

and if it was inverted it'd be:

```
def any_action(value: str) -> str:
    ...

any_action = my_decorator(any_action) 
any_action = action(any_action) # The signature of the my_decorator won't be correct for introspecting.
```

### Describe the solution you'd like to see

We could maybe make it work by not storing the reference and just storing the module/function name to get for calling but still introspecting on the given one (but it does have some caveats too).

**Comment by fabioz** [comment]
Note: investigate if functools.wraps adds info on the wrapper so that the original one can be gotten for introspection.

**Comment by kariharju** [comment]
This issue has been moved <a href="https://github.com/Sema4AI/actions/issues/51">here</a>, under <a href=https://github.com/Sema4AI/actions>Sema4AI/actions</a> repository.
