### ISSUE TITLE
Zombie process if killing action server with Ctrl+C multiple times.

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#235]
### Target components

action_server

### What is wrong

@mikahanninen: fyi, if I do stop AS quickly by double CTRL-C kombos then I am always left with one additional zombie process regardless any enters afterwards

### System info

Windows

**Comment by kariharju** [comment]
This issue has been moved <a href="https://github.com/Sema4AI/actions/issues/52">here</a>, under <a href=https://github.com/Sema4AI/actions>Sema4AI/actions</a> repository.
