### ISSUE TITLE
If there are more than 300 chars in description notify user about it (warn)

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#250]
### Target components

action_server

### Why & who

"In path /api/actions/google-sheets/add-sheet-rows/run, method post, operationId add_sheet_rows, description has length 514 exceeding limit of 300"
--> OpenAI only supports 300 chars for method descriptions. 

 could we highlight e.g. with yellow underline in VS Code if you go past that?

### Feature or enhancement

We should lint and notify user about it.

**Comment by fabioz** [comment]
@tonnitommi 
> I think in Action server it could be informational: "you might want to consider that this is not working with custom GPT". Some other platforms (like ReMark) don't have such a limit

**Comment by tonnitommi** [comment]
- Action (method) description max 300 chars
- Tested input arg and output description with ~10000 chars - did not hit a limit
- One OpenAPI spec can have max 30 "operations" - so Actions
