### ISSUE TITLE
Provide a way to see the logs directly in the run view when it fails.

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#252]
### Target components

action_server

### Why & who

@tonnitommi 
> it would be really nice to be able to access the log directly from this view where you started the run, especially when it fails

![image](https://github.com/robocorp/robocorp/assets/117621/e720d808-0382-4b81-b301-143488fc7df0)

### Feature or enhancement

Note; the run id should've been available, so, showing a link there should be reasonably straightforward.

**Comment by tonnitommi** [comment]
Also update to latest designs from Aleksey.
