### ISSUE TITLE
Support concurrency for `@action` in the same process (scaling Action Server)

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#270]
### Target components

action_server

### Why & who

Right now the Action Server creates a process where everything is scaled by the number of processes, so, it'll spawn a process to run one action and while that process is running that action, nothing else may be run in that same process.

This makes things simple, but also the maximum number of concurrent requests is based on the number of processes, which can be a heavyweight approach (as each new process needs its separate memory).

### Feature or enhancement

The proposed approach would be allowing concurrent `@action` calls in the same process using threads.

Note: changes are required both in the action server as well as in the actions and logging (because a different log may have to be created for each thread).

### Solution & alternative

- Why threads and not asyncio?
> asyncio would be harder to implement because the logging does not do well with it at this point and everything, including the user code needs to be async for it to be performant (as a single slow action with asyncio stops all the other asyncio tasks running concurrently).

**Comment by kariharju** [comment]
This issue has been moved <a href="https://github.com/Sema4AI/actions/issues/53">here</a>, under <a href=https://github.com/Sema4AI/actions>Sema4AI/actions</a> repository.
