### ISSUE TITLE
Action Server `--expose` is not currently handling requests in parallel

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#272]
### Target components

action_server

### What is wrong

Regardless of the internal support for concurrent requests, when used with `--expose` only one request is handled at a time.

### System info

Any OS.

**Comment by kariharju** [comment]
This also needs changes in the expose link proxy

**Comment by georgevetticaden** [comment]
any updates on this? @tonnitommi this prevents a lot of interesting things you can do with opengpt since the assistant does tool calls in parallel

**Comment by fabioz** [comment]
No updates currently, but it's already close to being tackled (see https://github.com/orgs/robocorp/projects/5).

**Comment by fabioz** [comment]
Fixed in https://github.com/robocorp/robocorp/commit/33a847aee024c6819025d86ef6f34398445731a1

Already available in the latest release (`action-server 0.1.4`).

**Comment by georgevetticaden** [comment]
tried it out on 0.1.4 and the asynch parallel ActionServerToolkit calls now work from openai_agent in opengpt. Great to see.
