### ISSUE TITLE
Action server react UI: API key doesn't seem to be passed to the action server when exposed.

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#306]
### Target components

action_server

### What is wrong

Reported by @cmin764:

I was testing AS 0.1.4 with the [greeter](https://github.com/robocorp/actions-cookbook/blob/chore/use-robocorp-2.0.0/greeter/package.yaml) (robocorp 2.0.0) example and during the normal private/local start everything works fine, but with the public exposure I get 403 Forbidden when triggering the action through the local URL.

Although is flaky, until I change the input value, it feels like is somehow caching the previous run’s auth and no matter the changes I bring in the “API Key” field, it uses what I used last time and resets the state when I finally affect the “Name” field, see recording below:

Recording at: https://sema4ai.slack.com/files/U028FHJR5HQ/F06QMEG6NN7/screen_recording_2024-03-21_at_12.27.05___pm.mov

### System info

Windows

**Comment by tonnitommi** [comment]
Confirmed, happens on all platforms, not just windows.
