### ISSUE TITLE
Format action output in local action server ui

### ISSUE THREAD

**Issue by tonnitommi** [robocorp/robocorp#307]
### Target components

action_server

### Why & who

For readability of the results

### Feature or enhancement

Format the string outputs of the actions in the UI. Newlines should be newlines. This would greatly improve readability.

<img width="745" alt="Screenshot 2024-03-22 at 7 21 35" src="https://github.com/robocorp/robocorp/assets/40179958/922f575f-9b28-432a-bbb8-af14b9a97012">

**Comment by fabioz** [comment]
As a note, there is existing code which does this formatting in the logging already:

https://github.com/robocorp/robocorp/blob/master/log/output-react/src/lib/prettyPrint.ts

Tests: https://github.com/robocorp/robocorp/blob/master/log/output-react/src/__tests__/testPrettyPrintVariables.ts

I guess we should try to use the same code (or if there's a better alternative, use it in both places).

**Comment by c02mo** [comment]
@fabioz We might need that as we're rendering the output with the help of the Code component. I've done a much simpler fix. Please take a look when you have time.
