### ISSUE TITLE
Add support for direct JSON payload input in Action Server UI run view

### ISSUE THREAD

**Issue by rihardsgravis** [robocorp/robocorp#310]
### Target components

action_server

### Why & who

For ease of use 

### Feature or enhancement

Direct raw JSON input should be supported in the Action Server run UI as an alternative to the form input. Would help a lot in ease of use when working with complex payloads

**Comment by fabioz** [comment]
Merged in https://github.com/robocorp/robocorp/commit/a9c8370ac95c6f21eaac3fd3b9878e132001702d
