### ISSUE TITLE
Drop the version field in package.yaml

### ISSUE THREAD

**Issue by kariharju** [robocorp/robocorp#340]
### Target components

action_server

### Why & who

The Action Package versioning can be handled in so many ways that adding a separate path for developer to maintain manually is not needed.

### Feature or enhancement

Drop the version field from the package.yaml spec and related parsers and validations.

**Comment by fabioz** [comment]
Note: when creating package create something as:

`action-package-<action-package-slugified-name>.zip`

and add `action-package*.zip` to the exclusion rules.

**Comment by fabioz** [comment]
Done (in sema4ai-action-server).
