### ISSUE TITLE
When the backend changes the action server UI doesn't reflect the changes

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#357]
What happens is the following:

The user starts the action server with `action-server start` and then goes on to the builtin UI. At that point he changes the action and restarts the action server: the builtin UI will still be bound to the old settings (so, for instance if the api key is now needed or the arguments are different, the UI won't work properly).

**Comment by kariharju** [comment]
This issue has been moved <a href="https://github.com/Sema4AI/actions/issues/56">here</a>, under <a href=https://github.com/Sema4AI/actions>Sema4AI/actions</a> repository.
