### ISSUE TITLE
Publish packages from action server to Control Room

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#361]
Simple python tester for the publish API: [https://github.com/robocorp/action_package_api_tester](https://github.com/robocorp/action_package_api_tester)

TODO: Integrate to action server.

New commands:

* cloud credentials
  * Prompt the user for API URL
    * Default to [cloud.robocorp.com](http://cloud.robocorp.com/)
  * Prompt the user for access credentials
  * Store the information locally
    * Use keyring
    * Get python-dbus from conda-forge
      * although we could also go for a 3rd party backend on Linux which wrote into a file ([https://pypi.org/project/keyring/#third-party-backends](https://pypi.org/project/keyring/#third-party-backends))
* package organizations
  * List all the organizations
    * access credentials
* package push
  * Push the package to Control Room
    * access credentials
    * org id
    * package name
    * package path
* package status
  * Get status of pushed package
    * access credentials
    * org id
    * package ID
* package publish
  * Publish the package
    * access credentials
  * Get organizations list
    * Ask user to select
  * Push the package
    * Prompt user to give package path
    * Prompt user to give package name
  * Get the package status
    * Loop until status
      * completed or published?
      * error

No UI sugar for the CLI commands. Keep them simple, don't add any libraries for command line handling.

Package publish:

* \~Organization listing\~
  * \~Keep the current UI\~
  * \~Add argument to provide the organization name and do not prompt the user unless org is not found\~
* \~Package path\~
  * \~Add an argument for the user to provide the path\~
  * \~If path is not provided, try to find the package zip file by it's default name from current folder\~
    * \~Cannot do this as there is no default name for the package…\~
  * \~Do not use input to get the path as auto complete is not provided for inputs\~

\~Package name\~

* \~Get the name from the package.yaml file\~
  * \~Unzip the the file\~
  * \~Read the yaml file\~

\~Package status\~

* \~Provide the URL to control room at start\~
* \~Remove the timeout\~
* \~Catch the keyboard interrupt and print that command was interrupted\~

JSON output

* Metadata command already has JSON handler
  \*
* ~Add JSON argument for package subcommands~
  * ~\[organizations, push, status\]~

\~Add new command:\~

* \~make_public\~
  * \~Will call the /publish API\~
  * \~This should not be called from the publish command. It needs always to be separate command (@kari)\~

\~Switch commands\~

* \~push -> upload\~

**Comment by kariharju** [comment]
Control Room API is now available and we have the specs for the secure login sequence as well.
