### ISSUE TITLE
how to call a action in a action to create a work flow?

### ISSUE THREAD

**Issue by himasai9712** [robocorp/robocorp#392]
### Target components

actions

### What is wrong

when i tried to use it my action is performing as normal python function

### System info

expected : to be running as another workflow and execute as sub action for code refer my question ==> [question url](https://stackoverflow.com/questions/78421128/how-to-call-a-action-in-another-action-in-robocorp-rpa-tool)

**Comment by fabioz** [comment]
Well, that's expected at this point... 

Are you using the action server for an AI use-case or RPA? What is you actual use case for wanting that to be different? Can you elaborate a bit on why would you like that?

**Comment by himasai9712** [comment]
@fabioz  Well I'm using action server one action is to call my data from an API end point and i want my another action to perform for my business logic as a action to create a workflow kind of thing here is me code:



```python
from datetime import datetime
from zoneinfo import ZoneInfo
import json
import pytz
from sema4ai.actions import action
# from robocorp.tasks import task
# from robocorp.tasks import task
import json
from helper_funtions import *

@action
def business_rule1(data: str) -> str:
    """
    Takes data and will do some business logic and return the update data

    Args:
        data (str): string data
    returns:
        str: returns updates string

    """
    data = data.replace('BOL_Number','test')
    # data = json.loads(data)
    return data

@action
def post_processing(pdf_path : str) -> str:

    """
    Takes pdf path and communicates with an API and returns json

    Args:

        pdf_path (str): local path of the pdf file
    
    Returns:
        dict: retruns the dictionary got from the api with some transformations

    
    """
    response = send_pdf_to_api(f"{pdf_path}","localhost:7009/extract_data/")
    if response.status_code == 200:  # Check for success
        response_data = response.text

    response_data = response_data.replace('json',"")
    response_data=response_data.replace("```","")
    shipping_data = json.loads(response_data)
    shipping_data = json.loads(shipping_data["outputs"][0])
    shipping_data = str(shipping_data)
    print(shipping_data)
    shipping_data = business_rule1(shipping_data)
   
    return shipping_data
```
By above code i was expecting my business rule function act as action but i can see it is acting as normal python function
is there any way like to do like sub actions or add tasks?

**Comment by fabioz** [comment]
There's really no support for that out of the box.

You can see all the intermediary calls (even for python functions) and its returns in the `log.html` generated, but it's really not recorded as a separate run in the action server.

What you could do is call the action server API to trigger those actions using the action server api doing a post request for it (you can access http://localhost:8080/docs to see the actual APIs available to run the actions), but note that each run will be recorded as an independent run and won't really appear as a subtask.

I still don't exactly know your use case though. The action server is geared towards AI GPTs use-case and not really RPA and it seems that what you want is more RPA than AI/LLMs, in which case the solution available is using the `Control Room` (from Sema4.ai, previously Robocorp), which has a concept of work-items (using robocorp-workitems) where you have one task generate work-items for other tasks to pick up, which may be closer to what you want.

**Comment by himasai9712** [comment]
I will try that robocorp-workitems @fabioz thanks

**Comment by fabioz** [comment]
As a note, the docs for it lies at: https://robocorp.com/docs/python/robocorp/robocorp-workitems (and for RPA, you'll be using `robocorp.tasks` instead of `sema4ai.actions`).

Closing this as there are no plans to implement this feature for the action server at this point.
