### ISSUE TITLE
Improve support for exceptions in the action server

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#403]
Right now a good error is not given when the action raises an error (it just says something about a process exiting with a non 0 value).

Rather, it should provide the error message.

The idea for this will be creating a new (`Response`) class which has `result/error` fields.

With that, actions which have the `Response` as the return value type in the schema will have the exception automatically handled and will then have a return as `Response(error="error message")`.

When everything works properly, actions would be expected to return `Response("result")` with the proper result.

Note that the action will return a `200` (Ok) even if an exception is raised in this case.

If an action doesn't return a `Response` and raises an exception a `500` code should still be returned, but the error message should show the exception message.

**Comment by cmin764** [comment]
I agree with the approach, thank you!

Would like to see more details on the last point:
> but the error message should show the exception message.

As I don't fully grasp what changes are needed here... is that for the server to reply with the actual error during a `500` so the LLM can understand and report that in the chat or? This sounds helpful, we just need to be careful to not accidentally expose something internal revealing too much about the code or something sensitive from the action body to the chat.

Then this has to be documented properly, including in our templates, so people would know how the action return type would also change behaviour (auto try-except with `200` when returning `Response`) and how the server behaves in different scenarios.

----

On the other hand, why not normalizing the behaviour straight from the server, thus all the actions responses would be wrapped by `Response`, removing the responsibility of the action return type to establish that. E.g.:
```python
MyModel:
    name
    email

def action() -> MyModel
```
And the chat always sees: `{result: {name, email}, error: null}` or `{result: null, error: "Error message"}`

Advocating for this mainly for two reasons:
1. I think we **shouldn't** affect server's behaviour based on the action return type. (I can already foresee support cases among devs, especially external ones)
2. I don't think it's developer responsibility to address infrastructure behaviour in the action code. The action code should focus strictly on the inner "meaty" logic itself and not worry about system behaviour. Also it would look ugly when actions type-annotates `Response[...]` and then, in the function body return, you'd have to do the wrapping explicitly, so why not focusing just on the inner meat?


Example:

```python
from sema4ai.actions import ResponseError

def action() -> MyModel:
    foo = {"Cosmin": "cosmin@email.com"}
    
    bar = foo["bad name"]  # 500 crash
    raise Exception(...)  # 500 crash
    raise ResponseError(message)  # 200 -> {error: message}
    
    name, email = foo.popitem()
    return MyModel(name=name, email=email)  # 200 -> {result: {name: Cosmin, email: cosmin@email.com}}
```

I think this would also enable devs to return quasi-primitives like `list[]`, `dict[]` without declaring models.

**Comment by fabioz** [comment]
I think we shouldn't automatically change the return from `MyModel` -> `Response` (the dev should've full control over that and us doing that automatically may not be what he wants).

I agree on the exception though, so, we can create a custom exception and only automatically wrap that one.

**Comment by cmin764** [comment]
> I think we shouldn't automatically change the return from `MyModel` -> `Response` (the dev should've full control over that and us doing that automatically may not be what he wants).
> 
> I agree on the exception though, so, we can create a custom exception and only automatically wrap that one.

If we expect to use the Action Server outside Agents/LLMs, then yes, we shouldn't be strict and forcing a response type here, I agree. Although if this will work with LLMs only and if the wrapping variation starts to open confusion tracks, then I don't see why this auto-wrapping would do more harm than good. One quick advantage against my proposal is that we don't introduce a breaking change by **not enabling** auto-wrapping a `Response`, so we leave it to the control of the dev.

Since I don't have a strong opinion here, use your best judgement here on the choice, but for the custom exception there's the strong opinion that we should leave that into the control of the dev mainly for security reasons.
